# Generated by Django 2.2.5 on 2019-10-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=300)),
                ('Description', models.TextField(max_length=500)),
                ('main_image', models.ImageField(upload_to='main_image/')),
                ('tags', models.ManyToManyField(to='awwwards.Tag')),
            ],
        ),
    ]
