# Generated by Django 2.2.5 on 2019-10-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0005_auto_20191019_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
