# Generated by Django 2.2.5 on 2019-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0011_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flags',
            field=models.URLField(null=True),
        ),
    ]
