# Generated by Django 2.2.5 on 2019-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0012_country_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://assets.awwwards.com/assets/images/pages/user/avatar.svg', upload_to='profile_pics/'),
        ),
    ]
