# Generated by Django 2.2.5 on 2019-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0013_auto_20191020_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
