# Generated by Django 2.2.5 on 2019-10-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0014_auto_20191020_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_image/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='awwwards.Post')),
            ],
            options={
                'verbose_name': 'posts',
            },
        ),
    ]
