# Generated by Django 2.2.5 on 2019-10-21 05:08

import awwwards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0015_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=awwwards.models.get_image_filename, verbose_name='Image'),
        ),
    ]
