# Generated by Django 2.2.5 on 2019-10-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0016_auto_20191021_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image'},
        ),
    ]
