# Generated by Django 2.2.5 on 2019-10-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0017_auto_20191021_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotd', to='awwwards.Post')),
            ],
        ),
    ]
