# Generated by Django 2.2.5 on 2019-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0018_sotd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='avarage',
            field=models.IntegerField(blank=True),
        ),
    ]
