# Generated by Django 2.2.5 on 2019-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0021_auto_20191021_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='avarage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creativity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
