# Generated by Django 2.2.5 on 2019-10-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0022_auto_20191021_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sotd',
            old_name='date',
            new_name='t_date',
        ),
    ]
