# Generated by Django 2.2.5 on 2019-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0023_auto_20191021_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_on',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
